apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: expense
  labels:
    app: web
    component: frontend #{{ .Values.label.component}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      component: frontend #{{ .Values.label.component}}
  template:
    metadata:
      labels:
        app: web
        component: frontend #{{ .Values.label.component}}
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 81
