apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.image }}
  labels:
    app: {{ .Values.app.image }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.image }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.image }}
    spec:
      containers:  # Fixed indentation here
        - name: {{ .Values.app.image }}
          image: {{ .Values.app.image }}:{{ .Values.version }}
          ports:
              - containerPort: {{ .Values.service.targetPort }}
