apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: expense
  labels:
    app: nginx
    tier: {{ .Values.label.component}}  
spec:
  selector:
    app: nginx
    tier: {{ .Values.label.component}}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer