apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.Namespace }}
  name: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    name : {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
